### ISSUE TITLE
Modify examples/evaluate_design/01_ten_bar_truss.html

### ISSUE THREAD

**Issue by ansDArnold** [pyansys/pyoptislang#113]
### Description of the modifications

```
plot_max_stress_lc1 = [abs(max(design.responses[1].value, key=abs))]
plot_max_stress_lc2 = [abs(max(design.responses[2].value, key=abs))]
```

The order of the responses are not secure enough to call with ids.
In my case the order is:
```
for r in design.responses:
    print(r.name)
    
stress_lc2
mass
stress
```

So there must be partly design change of the example

**Comment by PanekOndrej** [comment]
> I would propose to change into:
> 
> ```
> objectives = {obj.name: obj.value for obj in design.objectives}
> responses = {resp.name: resp.value for resp in design.responses}
> plot_mass_successfull = [(1, objectives['obj'])]
> plot_mass_unsuccessfull = []
> plot_max_stress_lc1 = [abs(max(responses['stress'], key=abs))]
> plot_max_stress_lc2 = [abs(max(responses['stress_lc2'], key=abs))]
> ```

Example was modified as You proposed. Thank you very much.
