### ISSUE TITLE
Bug located in TcpOslServer.start() method

### ISSUE THREAD

**Issue by PanekOndrej** [pyansys/pyoptislang#116]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

- when calling `start` on already evaluated project, execution is stuck because of `exec_started_listener` waiting for server notification `PROCESSING_STARTED` that is not delivered

Solution:
- check project status before sending `start` command (similarly as we do with `stop` command)
- check `run_scenario` or another property?

```
already_finished = False 
project_info = self._get_basic_project_info() 

run_scenario = project_info["projects"][0]["run_scenario"] 

if run_scenario == "FINISHED": 
   self._logger.warning("`START` command wasn't sent, project was already evaluated. 
                          If you wish to reevaluate it anyway, call `RESET` at first.") 
   return
```

### 📝 Steps to reproduce

- load already evaluated project
- run start
- (runs fine if `reset` is called before start)

```
from ansys.optislang.core import Optislang, examples

parametric_project = examples.get_files("calculator_with_params")[1][0]
osl = Optislang(
    project_path=parametric_project,
    loglevel="INFO",
)
# osl.reset()
osl.start()
osl.dispose()
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R2dev

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
n/a
```

**Comment by rfahlberg** [comment]
@PanekOndrej I'd expect that some other notification or error is returned. Something like "NOTHING_PROCESSED". Isn't that the case?

**Comment by PanekOndrej** [comment]
> @PanekOndrej I'd expect that some other notification or error is returned. Something like "NOTHING_PROCESSED". Isn't that the case?

You're right, server notification `NOTHING_PROCESSED` is returned indeed. We only need to add this to the list the `ExecStarted` listener's registered notifications and callback then.

**Comment by rfahlberg** [comment]
@PanekOndrej Alright, sounds good.
